ckpt_dir: /home/jin/graduate/checkpoints
vocab_dict: /home/jin/graduate/data/graduate/vocab.dict
w2v_model: /home/jin/graduate/word2vec/graduate/w2v_model
lda_model: /home/jin/graduate/LDA/graduate/model
lda_vocab: /home/jin/graduate/LDA/graduate/dict
num_classes: 263
max_gradient_norm: 5.0
batch_size: 1
num_hidden_units: 256
embedding_size: 150
num_layers: 2
dropout: 0.6
en_vocab_size: 200000
pos_weight: 1000